[versions]
ktor = "2.3.3"
kotlin-result = "1.1.18"

[libraries]
ktor-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor"}
ktor-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor"}
kotlin-result = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "kotlin-result"}
